apiVersion: v1
kind: Secret
metadata:
  name: ucto-jwt-secret
  namespace: ucto
type: Opaque
stringData:
  JWT_SECRET: "sngMLiQ+AWf4IKHvPakd//377ivmlx99fB46pfd8hHBq2lZP109hiUlQfaSfK1cqY7HtJovfX9rt+Ornzwv5CQ=="
