apiVersion: v1
kind: Secret
metadata:
  name: ucto-fast2sms
  namespace: ucto
type: Opaque
stringData:
  FAST2SMS_API_KEY: "rMOkPavS2ZiQAnT7qNC64IR9gtzeXxKWDbyHF3wEJmjfV1cdBprwIBVeXayYqcN0zbG5RmiQKW4vhnLj"
