import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

let traceabilityPanel: vscode.WebviewPanel | undefined;

export function activate(context: vscode.ExtensionContext) {
  console.log('UCTO extension activated');

  // --- UCTO: Init Project ---
  const initCommand = vscode.commands.registerCommand('ucto.init', async () => {
    const projectName = await vscode.window.showInputBox({
      prompt: 'Enter project name',
      placeHolder: 'my-ucto-project',
    });
    if (!projectName) return;

    const workspaceFolders = vscode.workspace.workspaceFolders;
    if (!workspaceFolders) {
      vscode.window.showErrorMessage('Please open a folder first');
      return;
    }

    const projectPath = path.join(workspaceFolders[0].uri.fsPath, projectName);
    try {
      // Create project structure
      fs.mkdirSync(path.join(projectPath, 'backend/src/main/java/com/ucto'), { recursive: true });
      fs.mkdirSync(path.join(projectPath, 'backend/src/main/resources'), { recursive: true });
      fs.mkdirSync(path.join(projectPath, 'frontend/lib'), { recursive: true });
      fs.mkdirSync(path.join(projectPath, 'docs'), { recursive: true });
      fs.mkdirSync(path.join(projectPath, '.github/workflows'), { recursive: true });

      // Create basic README
      fs.writeFileSync(path.join(projectPath, 'README.md'),
`# ${projectName}

Generated by UCTO - Agentic AI Platform for Automated Agile App Development

## Structure
- \`backend/\` - Spring Boot (Java)
- \`frontend/\` - Flutter + BLoC (Dart)
- \`docs/\` - Requirements, specs, traceability
`);

      vscode.window.showInformationMessage(`UCTO: Project '${projectName}' initialized successfully`);
    } catch (err: any) {
      vscode.window.showErrorMessage(`Failed to initialize project: ${err.message}`);
    }
  });

  // --- UCTO: Run Sprint ---
  const sprintCommand = vscode.commands.registerCommand('ucto.sprint', async () => {
    const sprintType = await vscode.window.showQuickPick(
      ['Planning', 'Design', 'Architecture Review', 'Compliance Check', 'Development', 'Testing', 'Review', 'Retrospective'],
      { placeHolder: 'Select sprint type' }
    );
    if (!sprintType) return;

    vscode.window.withProgress({
      location: vscode.ProgressLocation.Notification,
      title: `UCTO: Running ${sprintType} Sprint...`,
      cancellable: false,
    }, async (progress) => {
      progress.report({ message: 'Executing agent workflow...' });

      try {
        // Execute via CLI or API
        const backendUrl = vscode.workspace.getConfiguration('ucto').get('backendUrl', 'http://localhost:8080');
        // TODO: Call backend API to trigger sprint
        // const result = await fetch(`${backendUrl}/api/sprint`, { method: 'POST', ... });

        await new Promise(resolve => setTimeout(resolve, 2000)); // Simulate work
        vscode.window.showInformationMessage(`UCTO: ${sprintType} Sprint completed`);
      } catch (err: any) {
        vscode.window.showErrorMessage(`Sprint failed: ${err.message}`);
      }
    });
  });

  // --- UCTO: Trigger Agent ---
  const agentCommand = vscode.commands.registerCommand('ucto.agent', async () => {
    const agentType = await vscode.window.showQuickPick(
      ['BA', 'Developer', 'Tester', 'Compliance', 'UI/UX', 'Architect'],
      { placeHolder: 'Select agent to trigger' }
    );
    if (!agentType) return;

    const message = await vscode.window.showInputBox({
      prompt: `Message for ${agentType} Agent`,
      placeHolder: 'Enter instructions...',
    });

    if (!message) return;

    vscode.window.withProgress({
      location: vscode.ProgressLocation.Notification,
      title: `UCTO: ${agentType} Agent working...`,
      cancellable: false,
    }, async (progress) => {
      progress.report({ message: 'Processing...' });

      try {
        const backendUrl = vscode.workspace.getConfiguration('ucto').get('backendUrl', 'http://localhost:8080');
        // TODO: Call backend API to trigger agent
        // const result = await fetch(`${backendUrl}/api/agents/${agentType.toLowerCase()}/trigger`, { method: 'POST', body: JSON.stringify({ message }) });

        await new Promise(resolve => setTimeout(resolve, 1500));
        vscode.window.showInformationMessage(`UCTO: ${agentType} Agent completed`);
      } catch (err: any) {
        vscode.window.showErrorMessage(`Agent failed: ${err.message}`);
      }
    });
  });

  // --- UCTO: Deploy ---
  const deployCommand = vscode.commands.registerCommand('ucto.deploy', async () => {
    const environment = await vscode.window.showQuickPick(
      ['Development', 'Staging', 'Production'],
      { placeHolder: 'Select deployment environment' }
    );
    if (!environment) return;

    vscode.window.withProgress({
      location: vscode.ProgressLocation.Notification,
      title: `UCTO: Deploying to ${environment}...`,
      cancellable: false,
    }, async (progress) => {
      progress.report({ message: 'Building and deploying...' });

      try {
        // Execute Docker Compose build & deploy
        execSync('docker-compose build', { cwd: vscode.workspace.workspaceFolders?.[0]?.uri.fsPath, stdio: 'pipe' });
        execSync('docker-compose up -d', { cwd: vscode.workspace.workspaceFolders?.[0]?.uri.fsPath, stdio: 'pipe' });

        vscode.window.showInformationMessage(`UCTO: Deployed to ${environment} successfully`);
      } catch (err: any) {
        vscode.window.showErrorMessage(`Deploy failed: ${err.message}`);
      }
    });
  });

  // --- Traceability Panel ---
  const traceabilityCommand = vscode.commands.registerCommand('ucto.showTraceability', () => {
    if (traceabilityPanel) {
      traceabilityPanel.reveal(vscode.ViewColumn.Beside);
      return;
    }

    traceabilityPanel = vscode.window.createWebviewPanel(
      'uctoTraceability',
      'UCTO Traceability',
      vscode.ViewColumn.Beside,
      { enableScripts: true }
    );

    traceabilityPanel.webview.html = getTraceabilityHtml();
    traceabilityPanel.onDidDispose(() => { traceabilityPanel = undefined; });
  });

  // --- CI/CD Hooks Generation ---
  const cicdCommand = vscode.commands.registerCommand('ucto.generateCicd', async () => {
    const workspaceFolders = vscode.workspace.workspaceFolders;
    if (!workspaceFolders) {
      vscode.window.showErrorMessage('Please open a folder first');
      return;
    }

    const cicdPath = path.join(workspaceFolders[0].uri.fsPath, '.github/workflows/ucto-ci.yml');
    const cicdYaml = `name: UCTO CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven
      - name: Build Backend
        run: cd backend && ./mvnw clean package
      - name: Run Backend Tests
        run: cd backend && ./mvnw test

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Build Frontend
        run: cd frontend && flutter build web
      - name: Run Frontend Tests
        run: cd frontend && flutter test

  deploy:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to VPS
        run: |
          docker-compose build
          docker-compose up -d
`;

    try {
      fs.mkdirSync(path.dirname(cicdPath), { recursive: true });
      fs.writeFileSync(cicdPath, cicdYaml);
      vscode.window.showInformationMessage('UCTO: CI/CD workflow generated at .github/workflows/ucto-ci.yml');
    } catch (err: any) {
      vscode.window.showErrorMessage(`Failed to generate CI/CD: ${err.message}`);
    }
  });

  context.subscriptions.push(
    initCommand,
    sprintCommand,
    agentCommand,
    deployCommand,
    traceabilityCommand,
    cicdCommand
  );

  // Register traceability view
  vscode.window.registerTreeDataProvider('uctoTraceabilityView', new TraceabilityDataProvider());
}

function getTraceabilityHtml(): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>UCTO Traceability</title>
  <style>
    body { font-family: system-ui, sans-serif; padding: 16px; color: var(--vscode-foreground); }
    h2 { color: var(--vscode-editor-foreground); font-size: 16px; margin-bottom: 12px; }
    .card { background: var(--vscode-editor-background); border: 1px solid var(--vscode-widget-border); border-radius: 6px; padding: 12px; margin-bottom: 8px; }
    .label { color: var(--vscode-textSecondary-foreground); font-size: 11px; text-transform: uppercase; }
    .value { font-size: 13px; margin-top: 2px; }
    .status-badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; }
    .approved { background: #22c55e20; color: #22c55e; border: 1px solid #22c55e40; }
    .pending { background: #f59e0b20; color: #f59e0b; border: 1px solid #f59e0b40; }
    .in-review { background: #3b82f620; color: #3b82f6; border: 1px solid #3b82f640; }
  </style>
</head>
<body>
  <h2>📋 Traceability Matrix</h2>
  <div class="card">
    <div class="label">Unified Signup/Signin</div>
    <div class="value">BRD, UCD — <span class="status-badge approved">Approved</span></div>
  </div>
  <div class="card">
    <div class="label">Role-based Access</div>
    <div class="value">BRD, UCD — <span class="status-badge approved">Approved</span></div>
  </div>
  <div class="card">
    <div class="label">Audit Logs</div>
    <div class="value">BRD, TCD — <span class="status-badge in-review">In Review</span></div>
  </div>
  <div class="card">
    <div class="label">Compliance Enforcement</div>
    <div class="value">BRD, TCD — <span class="status-badge approved">Approved</span></div>
  </div>
  <div class="card">
    <div class="label">UI/UX Design</div>
    <div class="value">UCD — <span class="status-badge approved">Approved</span></div>
  </div>
  <div class="card">
    <div class="label">Architectural Guidance</div>
    <div class="value">UCD — <span class="status-badge pending">Pending</span></div>
  </div>
  <div class="card">
    <div class="label">CLI Extension</div>
    <div class="value">UCD — <span class="status-badge pending">Pending</span></div>
  </div>
  <h2 style="margin-top: 20px;">📊 Recent Activity</h2>
  <div class="card"><div class="label">Just now</div><div class="value">Extension activated</div></div>
</body>
</html>`;
}

class TraceabilityDataProvider implements vscode.TreeDataProvider<{ key: string; label: string; status: string }> {
  private _onDidChangeTreeData = new vscode.EventEmitter<void>();
  readonly onDidChangeTreeData = this._onDidChangeTreeData.event;

  getTreeItem(element: { key: string; label: string; status: string }): vscode.TreeItem {
    const item = new vscode.TreeItem(element.label);
    item.description = element.status;
    item.tooltip = `${element.label}: ${element.status}`;
    item.contextValue = element.key;
    return item;
  }

  getChildren(): { key: string; label: string; status: string }[] {
    return [
      { key: 'signup', label: 'Unified Signup/Signin', status: '✅ Approved' },
      { key: 'roles', label: 'Role-based Access', status: '✅ Approved' },
      { key: 'audit', label: 'Audit Logs', status: '🔍 In Review' },
      { key: 'compliance', label: 'Compliance Enforcement', status: '✅ Approved' },
      { key: 'uiux', label: 'UI/UX Design', status: '✅ Approved' },
      { key: 'arch', label: 'Architectural Guidance', status: '⏳ Pending' },
      { key: 'cli', label: 'CLI Extension', status: '⏳ Pending' },
    ];
  }
}

export function deactivate() {
  console.log('UCTO extension deactivated');
}
